services:
  postgres:
    image: 'postgres:17'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_STORENAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - goapp_network

  goapp:
    image: cosmtrek/air:latest #change to golang:version
    volumes:
      - ${PWD}:/app
    working_dir: /app
    tty: true
    environment:
      TEMPLATES_BASEPATH: /app/cmd/server/http/web/templates
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_STORENAME: ${POSTGRES_STORENAME}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '8080:8080'
      - '2000:2000'
    depends_on:
      - postgres
    networks:
      - goapp_network

networks:
  goapp_network:

volumes:
  postgres_data:
